apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redisclusters.redis.kun
spec:
  group: redis.kun
  names:
    kind: RedisCluster
    listKind: RedisClusterList
    plural: redisclusters
    singular: rediscluster
  scope: Namespaced
  additionalPrinterColumns:
  - JSONPath: .spec.size
    description: The number of Redis node in the ensemble
    name: Size
    type: integer
  - JSONPath: .status.conditions[].type
    description: The status of Redis Cluster
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            affinity:
              type: object
            command:
              items:
                type: string
              type: array
            config:
              additionalProperties:
                type: string
              type: object
            disablePersistence:
              type: boolean
            exporter:
              properties:
                enabled:
                  type: boolean
                image:
                  type: string
              type: object
            image:
              type: string
            password:
              type: string
              maxLength: 48
            resources:
              type: object
            securityContext:
              type: object
            sentinel:
              description: Sentinel defines its cluster settings
              properties:
                affinity:
                  type: object
                command:
                  items:
                    type: string
                  type: array
                customConfig:
                  items:
                    type: string
                  type: array
                image:
                  type: string
                replicas:
                  format: int32
                  type: integer
                resources:
                  type: object
                securityContext:
                  type: object
                tolerations:
                  items:
                    type: object
                  type: array
              type: object
            shutdownConfigMap:
              type: string
            size:
              format: int32
              type: integer
              minimum: 3
              maximum: 10
            storage:
              properties:
                emptyDir:
                  type: object
                keepAfterDeletion:
                  type: boolean
                persistentVolumeClaim:
                  type: object
              type: object
            toleRations:
              items:
                type: object
              type: array
          type: object
        status:
          properties:
            conditions:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Status of cluster condition.
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            masterIP:
              type: string
            sentinelIP:
              type: string
          type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
